version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: notes_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: notes_app

  backend:
    build: ./backend
    container_name: notes_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/notes_app
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/__pycache__

  frontend:
    build: ./frontend
    container_name: notes_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
